export const textZh = {
    title: '住房系统',
    sellableHomes: '房源',
    roleBinding: '已有住房',
    recommendHousing: '给无房角色推荐住房',
    recommendHome: '推荐住房',
    assignHome: '直接指派住房',
    recentChains: '最近租房链路',
    moveInCost: '入住成本',
    currentHome: '当前住处',
    selectedHome: '本次房源',
    latestChain: '最新链路',
    noChain: '暂无链路',
    eligibleRole: '选择无房角色',
    noHomelessCharacters: '暂无无房角色',
    noHousedCharacters: '暂无已有住房角色',
    noAvailableHomes: '暂无启用房源',
    noHousingActionTarget: '所有角色都有住处，推荐/指派入口暂时关闭。',
    housedActionHint: '本区只处理无房角色；已有住房的角色在“已有住房”区查看/管理。',
    viewDialogue: '看房对话',
    viewSummary: '看房总结',
    consideration: '考虑',
    decision: '决定',
    agent: '中介',
    character: '角色',
    chainRunning: '链路执行中...',
    chainResult: '链路结果',
    chainFailed: '链路失败',
    agencyAi: '中介所 AI',
    roomAssembly: '样板间组装实验',
    openRoomAssembly: '打开组装窗口',
    generateRoomAssembly: '中介生成并保存',
    roomAssemblySaved: '已生成并保存到实际房间。',
    loading: '住房系统加载中...',
    loadFailed: '住房系统加载失败',
    requestFailed: '请求失败 ',
    save: '保存配置',
    run: '手动执行',
    retry: '重新生成',
    clearError: '删除报错',
    enable: '启用中介所',
    disable: '关闭中介所',
    lastAd: '上次广告',
    nextAd: '下次广告',
    lastFailure: '上次失败',
    noAds: '还没有广告记录。',
    published: '已公告',
    manual: '手动',
    auto: '自动',
    agencyFailed: '中介所 AI 执行失败：',
    classProfiles: '阶层与租客画像',
    classProfilesHint: '这些画像会影响租房偏好、消费倾向和社交门槛。',
    addClass: '保存阶层',
    className: '阶层名称',
    classEmoji: '图标',
    classDescription: '画像描述',
    workBias: '工作倾向',
    consumptionBias: '消费倾向',
    prestigeBias: '体面倾向',
    socialBarrier: '社交门槛',
    commonLocations: '常见地点',
    emptyClasses: '还没有阶层画像。',
    walletRefreshed: '已刷新付款角色钱包。',
    officeName: '门店名称',
    agentName: '顾问名称',
    officeDistrict: '门店分区',
    businessScope: '业务范围',
    intervalHours: '决策间隔（小时）',
    autoModel: '自动选择可用 API',
    adStyle: '广告风格',
    prompt: '人格提示，可留空',
    applyStyle: '套用风格',
    catalog: '房源库',
    custom: '自定义',
    addHome: '新增房子',
    saveEdit: '保存编辑',
    cancel: '取消编辑',
    edit: '编辑',
    remove: '删除',
    removeAd: '删除记录',
    enabledState: '启用中',
    disabledState: '已停用',
    homeName: '房子名字',
    weeklyRent: '每周租金',
    deposit: '押金',
    buyout: '售价/买断价',
    comfort: '舒适度',
    prestige: '体面感',
    privacy: '隐私感',
    sortOrder: '显示排序',
    desc: '介绍',
    id: 'ID',
    emoji: 'Emoji',
    applyHome: '加入可推销列表',
    applyExistingHome: '已在列表中，去编辑',
    homeApplied: '这套房子已经加入已保存的房子，中介 AI 现在可以直接拿它发广告。',
    homeOpened: '这套房子已经在列表里了，我已经帮你打开编辑。',
    modalCustomHome: '自定义房子',
    modalEditHome: '编辑房子',
    emptyHomes: '还没有可推销的房子。',
    roleName: '角色',
    wallet: '钱包',
    unknown: 'unknown',
    idle: 'idle',
    unboundHousing: '未绑定住房',
    stable: '稳定居住',
    homeless: '无固定住所',
    temporary: '临时落脚',
    unstable: '居住不稳',
    overdue: '租金拖欠',
    note: '备注',
    rentDue: '催租日',
    nextRentDue: '下次催租',
    missedRent: '拖欠次数',
    status: '状态',
    record: '记录',
    generatedViewingRecord: '已生成看房记录，展开查看完整内容。',
    dialogueCount: '条对话',
    viewingRecord: '看房记录',
    collapse: '收起',
    expand: '展开',
    budget: '预算',
    furnitureShop: '家具商店',
    scaleProfile: '比例标尺',
    itemCount: '件',
    classCount: '类',
    savedAssets: '已保存素材',
    spent: '花费',
    purchased: '购买',
    roomAssemblyHint: '实验版会直接覆盖当前像素小屋布局，并保存到浏览器本地房间存储。',
    roomAssemblyCopy:
        '点生成后，中介 AI 会读取房间网格、完整家具商店、每件家具价格和当前房源预算，自行采购并摆放；保存完成后去“像素小屋”即可看到实际房间已经变成这套布局。',
    customHomeHint: '这里是少数情况才需要手动改的详细资料。',
    payRent: '交房租',
    saving: '保存中...',
    untriggered: '未触发',
    agencyPlaceholder: '商业街',
    assignedHome: '已指派住房',
    signed: '已签约',
    declined: '已拒绝',
    rejectedInsufficientFunds: '余额不足被拒',
    completed: '已完成',
};

export const textEn = {
    title: 'Housing System',
    sellableHomes: 'Listings',
    roleBinding: 'Housed Roles',
    recommendHousing: 'Recommend Housing to Homeless Roles',
    recommendHome: 'Recommend Home',
    assignHome: 'Assign Home',
    recentChains: 'Recent Rental Chains',
    moveInCost: 'Move-in Cost',
    currentHome: 'Current Home',
    selectedHome: 'Selected Home',
    latestChain: 'Latest Chain',
    noChain: 'No chain yet',
    eligibleRole: 'Homeless Role',
    noHomelessCharacters: 'No homeless roles',
    noHousedCharacters: 'No housed roles',
    noAvailableHomes: 'No enabled listings',
    noHousingActionTarget: 'All roles already have housing. Recommendation and assignment are temporarily closed.',
    housedActionHint:
        'This area only handles homeless roles. Housed roles can be viewed or managed in the Housed Roles section.',
    viewDialogue: 'Viewing Dialogue',
    viewSummary: 'Viewing Summary',
    consideration: 'Consideration',
    decision: 'Decision',
    agent: 'Agent',
    character: 'Character',
    chainRunning: 'Chain running...',
    chainResult: 'Chain result',
    chainFailed: 'Chain failed',
    agencyAi: 'Agency AI',
    roomAssembly: 'Showroom Assembly Lab',
    openRoomAssembly: 'Open Assembly Window',
    generateRoomAssembly: 'Generate & Save',
    roomAssemblySaved: 'Generated and saved to the actual room.',
    loading: 'Loading housing system...',
    loadFailed: 'Failed to load housing system',
    requestFailed: 'Request failed ',
    save: 'Save Config',
    run: 'Run Manually',
    retry: 'Regenerate',
    clearError: 'Clear Error',
    enable: 'Enable Agency',
    disable: 'Disable Agency',
    lastAd: 'Last Ad',
    nextAd: 'Next Ad',
    lastFailure: 'Last Failure',
    noAds: 'No ad records yet.',
    published: 'Published',
    manual: 'Manual',
    auto: 'Auto',
    agencyFailed: 'Agency AI failed:',
    classProfiles: 'Class & Tenant Profiles',
    classProfilesHint: 'These profiles influence rent preference, spending bias, and social barriers.',
    addClass: 'Save Class',
    className: 'Class Name',
    classEmoji: 'Icon',
    classDescription: 'Profile Description',
    workBias: 'Work Bias',
    consumptionBias: 'Consumption Bias',
    prestigeBias: 'Prestige Bias',
    socialBarrier: 'Social Barrier',
    commonLocations: 'Common Locations',
    emptyClasses: 'No class profiles yet.',
    walletRefreshed: 'Payer wallet refreshed.',
    officeName: 'Office Name',
    agentName: 'Agent Name',
    officeDistrict: 'Office District',
    businessScope: 'Business Scope',
    intervalHours: 'Decision Interval (hours)',
    autoModel: 'Auto-select available API',
    adStyle: 'Ad Style',
    prompt: 'Persona prompt, optional',
    applyStyle: 'Apply Style',
    catalog: 'Listing Library',
    custom: 'Custom',
    addHome: 'Add Home',
    saveEdit: 'Save Edit',
    cancel: 'Cancel Edit',
    edit: 'Edit',
    remove: 'Delete',
    removeAd: 'Delete Record',
    enabledState: 'Enabled',
    disabledState: 'Disabled',
    homeName: 'Home Name',
    weeklyRent: 'Weekly Rent',
    deposit: 'Deposit',
    buyout: 'Sale / Buyout Price',
    comfort: 'Comfort',
    prestige: 'Prestige',
    privacy: 'Privacy',
    sortOrder: 'Display Order',
    desc: 'Description',
    id: 'ID',
    emoji: 'Emoji',
    applyHome: 'Add to Sellable List',
    applyExistingHome: 'Already listed, edit it',
    homeApplied: 'This home has been added to saved listings. The agency AI can now advertise it directly.',
    homeOpened: 'This home is already listed, so I opened it for editing.',
    modalCustomHome: 'Custom Home',
    modalEditHome: 'Edit Home',
    emptyHomes: 'No sellable homes yet.',
    roleName: 'Role',
    wallet: 'Wallet',
    unknown: 'unknown',
    idle: 'idle',
    unboundHousing: 'No Housing Bound',
    stable: 'Stable Housing',
    homeless: 'Homeless',
    temporary: 'Temporary Stay',
    unstable: 'Unstable Housing',
    overdue: 'Rent Overdue',
    note: 'Note',
    rentDue: 'Rent Due',
    nextRentDue: 'Next Rent Due',
    missedRent: 'Missed Rent',
    status: 'Status',
    record: 'Record',
    generatedViewingRecord: 'Viewing record generated. Expand to read the full content.',
    dialogueCount: 'dialogue lines',
    viewingRecord: 'Viewing Record',
    collapse: 'Collapse',
    expand: 'Expand',
    budget: 'Budget',
    furnitureShop: 'Furniture Shop',
    scaleProfile: 'Scale Profile',
    itemCount: 'items',
    classCount: 'types',
    savedAssets: 'Saved Assets',
    spent: 'Spent',
    purchased: 'Purchased',
    roomAssemblyHint:
        'Experimental mode directly overwrites the current pixel room layout and saves it to local room storage.',
    roomAssemblyCopy:
        'After generation, the agency AI reads the room grid, furniture shop, item prices, and listing budget, then buys and places furniture automatically. When saved, open Pixel Cottage to see the actual room updated.',
    customHomeHint: 'Detailed data for the few cases that need manual edits.',
    payRent: 'Pay Rent',
    saving: 'Saving...',
    untriggered: 'Not triggered',
    agencyPlaceholder: 'City Street',
    assignedHome: 'Home assigned',
    signed: 'Signed',
    declined: 'Declined',
    rejectedInsufficientFunds: 'Rejected: insufficient funds',
    completed: 'Completed',
    housedCount: 'housed',
    homeUnit: 'homes',
    perWeek: 'week',
    aiGenerating: 'AI generating...',
};

export const text = new Proxy(textZh, {
    get(target, prop) {
        const lang = typeof localStorage !== 'undefined' ? localStorage.getItem('chatpulse_lang') : 'zh';
        const pack = lang === 'en' ? textEn : target;
        return pack[prop] ?? target[prop] ?? String(prop);
    },
});

export const homePresets = [
    {
        key: 'old_apartment_chunheli',
        title: '老破小',
        subtitle: '春和里 4栋302',
        values: {
            id: 'old_apartment_chunheli_4_302',
            name: '春和里小区 4栋302',
            emoji: '🏚️',
            weekly_rent: 22,
            deposit: 40,
            sale_price: 380,
            comfort: 8,
            prestige: 2,
            privacy: 4,
            description:
                '一室一厅，老式水泥楼，五楼步梯，屋里采光一般但通风还行。家具旧，墙皮有点起鼓，厨房很小，卫生间是老式布局。优点是便宜、离便利店近、对刚落脚的人压力最小；缺点是压抑、隔音差、夏天闷、体面感很弱。',
        },
    },
    {
        key: 'shared_room_xinyuan',
        title: '合租单间',
        subtitle: '欣园公寓 2单元801-A室',
        values: {
            id: 'shared_room_xinyuan_2_801',
            name: '欣园公寓 2单元801-A室',
            emoji: '🛏️',
            weekly_rent: 28,
            deposit: 60,
            sale_price: 0,
            comfort: 12,
            prestige: 6,
            privacy: 8,
            description:
                '三室一厅里的朝南次卧，简约出租房风格，床、衣柜、书架都有，公共区域和另外两位租客共用。优点是预算友好、生活机能方便、房间基本齐全；缺点是要看室友脸色，做饭和洗澡高峰期会挤，真正的私人空间有限。',
        },
    },
    {
        key: 'shared_flat_jingan',
        title: '普通合租',
        subtitle: '静安新村 6栋502',
        values: {
            id: 'shared_flat_jingan_6_502',
            name: '静安新村 6栋502',
            emoji: '🏠',
            weekly_rent: 35,
            deposit: 80,
            sale_price: 0,
            comfort: 18,
            prestige: 10,
            privacy: 14,
            description:
                '两室一厅标准合租，日常居住氛围比较稳定，客厅和厨房都能正常使用，装修是普通白墙木地板风格。优点是住法最常见、性价比稳、位置不偏；缺点是没什么惊喜，房子本身偏普通，谈不上特别舒服或特别有面子。',
        },
    },
    {
        key: 'studio_yuecheng',
        title: '独立公寓',
        subtitle: '悦城公馆 11楼1107',
        values: {
            id: 'studio_yuecheng_11_1107',
            name: '悦城公馆 11楼1107',
            emoji: '🏢',
            weekly_rent: 58,
            deposit: 120,
            sale_price: 980,
            comfort: 28,
            prestige: 22,
            privacy: 24,
            description:
                '一室户带独立卫浴和小厨房，现代简装，采光不错，晚上回家会有比较完整的个人空间。优点是安静、独处感强、适合想把生活收回自己手里的人；缺点是租金明显更高，空间不算大，长期住会开始在意收纳。',
        },
    },
    {
        key: 'riverside_lanwan',
        title: '江景公寓',
        subtitle: '澜湾国际 17楼1703',
        values: {
            id: 'riverside_lanwan_17_1703',
            name: '澜湾国际 17楼1703',
            emoji: '🌉',
            weekly_rent: 95,
            deposit: 220,
            sale_price: 1680,
            comfort: 40,
            prestige: 38,
            privacy: 32,
            description:
                '两室一厅带大落地窗，偏现代轻奢风，客厅能看到江景，白天和夜景都很能撑场面。优点是舒适、体面、很适合约人来家里坐；缺点是贵，生活成本会被整体抬高，住进去之后很难再接受太差的房子。',
        },
    },
    {
        key: 'luxury_loft_jinyu',
        title: '高档 loft',
        subtitle: '金域中心 23楼2301',
        values: {
            id: 'luxury_loft_jinyu_23_2301',
            name: '金域中心 23楼2301 loft',
            emoji: '🌇',
            weekly_rent: 150,
            deposit: 360,
            sale_price: 2880,
            comfort: 48,
            prestige: 55,
            privacy: 38,
            description:
                '挑高 loft，两层分区明显，下层会客、上层休息，整体偏深色高端都市风，电梯厅和物业都很讲排面。优点是圈层感强、很适合做身份展示、拍照和待客都上镜；缺点是租金和押金都高，对收入和消费习惯要求也高。',
        },
    },
];

export const homePresetEn = {
    old_apartment_chunheli: { title: 'Old Walk-up', subtitle: 'Chunheli 4-302' },
    shared_room_xinyuan: { title: 'Shared Room', subtitle: 'Xinyuan Apt 2-801A' },
    shared_flat_jingan: { title: 'Standard Share', subtitle: 'Jingan New Village 6-502' },
    studio_yuecheng: { title: 'Studio Apartment', subtitle: 'Yuecheng Mansion 1107' },
    riverside_lanwan: { title: 'Riverside Apartment', subtitle: 'Lanwan International 1703' },
    luxury_loft_jinyu: { title: 'Luxury Loft', subtitle: 'Jinyu Center 2301' },
};

export const promptStyles = [
    {
        key: 'street',
        label: '街头招揽',
        prompt: '你像商业街口发传单的中介一样说话，语气直接、接地气、能快速把价格和房子优点说清楚。',
    },
    {
        key: 'warm',
        label: '温和推荐',
        prompt: '你像认真替人找房的顾问一样说话，先把房子适合谁讲清楚，再自然带出价格和卖点。',
    },
    {
        key: 'budget',
        label: '穷人友好',
        prompt: '你主打低预算租客，广告里优先强调租金、押金、性价比和适合刚落脚的人。',
    },
    { key: 'luxury', label: '体面高端', prompt: '你主打体面和高端感，广告里优先强调地段、空间、圈层感和价格。' },
    {
        key: 'sellfast',
        label: '急租/急售',
        prompt: '你像急租急售的中介，广告简短有力，必须先报价格，再说房型和核心卖点。',
    },
];

export const promptStyleLabelsEn = {
    street: 'Street Pitch',
    warm: 'Warm Recommendation',
    budget: 'Budget Friendly',
    luxury: 'Premium & Polished',
    sellfast: 'Urgent Rent/Sale',
};

export const defaultDistrictOptions = [
    { id: 'street', name: '商业街' },
    { id: 'home', name: '家' },
    { id: 'restaurant', name: '餐厅' },
    { id: 'convenience', name: '便利店' },
    { id: 'park', name: '中央公园' },
    { id: 'mall', name: '商场' },
    { id: 'school', name: '夜校' },
    { id: 'hospital', name: '医院' },
    { id: 'factory', name: '工厂' },
    { id: 'casino', name: '地下赌场' },
    { id: 'hacker', name: '黑客据点' },
];

export const defaultDistrictNameEn = {
    street: 'City Street',
    home: 'Home',
    restaurant: 'Restaurant',
    convenience: 'Convenience Store',
    park: 'Central Park',
    mall: 'Mall',
    school: 'Night School',
    hospital: 'Hospital',
    factory: 'Factory',
    casino: 'Underground Casino',
    hacker: 'Hacker Hideout',
};

export const emptyHome = {
    id: '',
    name: '',
    emoji: '',
    description: '',
    weekly_rent: 0,
    deposit: 0,
    sale_price: 0,
    comfort: 0,
    prestige: 0,
    privacy: 0,
    is_enabled: 1,
    sort_order: 0,
};

export const emptySocialClass = {
    id: '',
    name: '',
    emoji: '🧩',
    description: '',
    work_bias: 0,
    consumption_bias: 0,
    prestige_bias: 0,
    social_barrier: 0,
    common_locations: '',
    is_enabled: 1,
    sort_order: 0,
};

export const emptyAgency = {
    enabled: 1,
    agency_name: '',
    agent_name: '',
    office_district: 'street',
    business_scope: '',
    persona_prompt: '',
    decision_interval_hours: 6,
    model_char_id: 'auto',
    next_ad_at: 0,
    last_ad_at: 0,
    last_error: '',
    last_error_at: 0,
};
