// Existing table definitions. Column defaults and schema order are compatibility contracts.
module.exports = {
    characters: `
        CREATE TABLE IF NOT EXISTS characters (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            avatar TEXT,
            avatar_frame TEXT DEFAULT '',
            persona TEXT,
            world_info TEXT,
            api_endpoint TEXT,
            api_key TEXT,
            model_name TEXT,
            memory_api_endpoint TEXT,
            memory_api_key TEXT,
            memory_model_name TEXT,
            tts_enabled INTEGER DEFAULT 0,
            tts_provider TEXT DEFAULT 'tencent',
            tts_api_key TEXT DEFAULT '',
            tts_voice TEXT DEFAULT '',
            tts_model TEXT DEFAULT '',
            tts_endpoint TEXT DEFAULT '',
            tts_trigger_mode TEXT DEFAULT 'tagged',
            tts_autoplay INTEGER DEFAULT 0,
            interval_min INTEGER DEFAULT 10,
            interval_max INTEGER DEFAULT 120,
            affinity INTEGER DEFAULT 50,
            initial_affinity INTEGER DEFAULT 50,
            status TEXT DEFAULT 'active',
            pressure_level INTEGER DEFAULT 0,
            created_at INTEGER DEFAULT 0,
            last_user_msg_time INTEGER DEFAULT 0,
            is_blocked INTEGER DEFAULT 0,
            system_prompt TEXT,
            is_diary_unlocked INTEGER DEFAULT 0,
            hidden_state TEXT DEFAULT '',
            jealousy_level INTEGER DEFAULT 0,
            jealousy_target TEXT DEFAULT '',
            city_reply_pending INTEGER DEFAULT 0,
            city_ignore_streak INTEGER DEFAULT 0,
            city_last_outreach_at INTEGER DEFAULT 0,
            city_post_ignore_reaction INTEGER DEFAULT 0,
            city_status_started_at INTEGER DEFAULT 0,
            city_status_until_at INTEGER DEFAULT 0,
            city_medical_last_recovery_at INTEGER DEFAULT 0,
            stat_int INTEGER DEFAULT 50,
            stat_sta INTEGER DEFAULT 50,
            stat_cha INTEGER DEFAULT 50,
            energy INTEGER DEFAULT 100,
            sleep_debt INTEGER DEFAULT 0,
            sleep_pressure INTEGER DEFAULT 20,
            mood INTEGER DEFAULT 50,
            stress INTEGER DEFAULT 20,
            social_need INTEGER DEFAULT 50,
            explicit_emotion_state TEXT DEFAULT '',
            health INTEGER DEFAULT 100,
            satiety INTEGER DEFAULT 45,
            stomach_load INTEGER DEFAULT 0,
            work_distraction INTEGER DEFAULT 0,
            sleep_disruption INTEGER DEFAULT 0,
            llm_debug_capture INTEGER DEFAULT 1,
            sweep_limit INTEGER DEFAULT 30,
            sweep_initialized INTEGER DEFAULT 1,
            sweep_last_error TEXT DEFAULT '',
            sweep_last_run_at INTEGER DEFAULT 0,
            sweep_last_success_at INTEGER DEFAULT 0,
            sweep_last_saved_count INTEGER DEFAULT 0,
            private_summary_threshold INTEGER DEFAULT 30,
            private_summary_last_error TEXT DEFAULT '',
            private_summary_last_run_at INTEGER DEFAULT 0,
            private_summary_last_success_at INTEGER DEFAULT 0,
            private_summary_baseline_message_id INTEGER DEFAULT 0,
            impression_q_limit INTEGER DEFAULT 3,
            context_msg_limit INTEGER DEFAULT 60
        );

        `,
    emotion_logs: `CREATE TABLE IF NOT EXISTS emotion_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            character_id TEXT NOT NULL,
            source TEXT NOT NULL,
            reason TEXT DEFAULT '',
            old_state TEXT DEFAULT '',
            new_state TEXT DEFAULT '',
            old_mood INTEGER,
            new_mood INTEGER,
            old_stress INTEGER,
            new_stress INTEGER,
            old_social_need INTEGER,
            new_social_need INTEGER,
            old_pressure INTEGER,
            new_pressure INTEGER,
            old_jealousy INTEGER,
            new_jealousy INTEGER,
            timestamp INTEGER NOT NULL
        );

        `
};
